-- 코드를 입력하세요
SELECT FLAVOR
FROM (SELECT A.FLAVOR, SUM(A.TOTAL_ORDER + NVL(B.TOTAL_ORDER, 0)) C
FROM JULY A LEFT JOIN FIRST_HALF B USING (SHIPMENT_ID)
GROUP BY A.FLAVOR
ORDER BY C DESC)
WHERE ROWNUM <= 3;

 
